name = "ndisidore-bard-of-love"
main = "src/index.js"
compatibility_date = "2024-01-17"

rules = [{ type = "Text", globs = ["**/*.ndjson"], fallthrough = true }]

[[vectorize]]
binding = "VECTORIZE_INDEX"
index_name = "ndisidore-poems"

[ai]
binding = "AI"
