name = "cheekfreaks"
main = "src/index.js"
compatibility_date = "2024-01-17"

[[vectorize]]
binding = "VECTORIZE_INDEX"
index_name = "lyrics"

[[r2_buckets]]
binding = "LYRICS_BUCKET"
bucket_name = "lyrics"
preview_bucket_name = "lyrics"

[ai]
binding = "AI"
